version: '3.8'
services: 
  database:
    image: mysql:8.0.19
    ports: 
      - '3306:3306'
    volumes: 
      - ./data:/var/lib/mysql
      - ./db-init.sql:/docker-entrypoint-initdb.d'
    env_file: 
      - db.env
  
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    volumes: 
      - ./backend:/app
    ports: 
      - '5000:5000'

    depends_on: 
      - 'database'

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    volumes: 
      - ./frontend:/app
    ports: 
      - '3000:3000'
    depends_on: 
      - 'backend'
