version: '3.8'
services: 
  # database:
  #   image: mysql:8.0.19
  #   env_file: 
  #     - db.env
  
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports: 
      - '5000:5000'
    
    # volumes:
    #   - ./backend

  # frontend: