version: '3.8'
services: 
  database:
    image: mysql:8.0.19
    env_file: 
      - db.env
  
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    volumes: 
      - ./backend:/app
    ports: 
      - '5000:5000'

    depends_on: 
      - 'db'
    
    # volumes:
    #   - ./backend

  # frontend: